### ISSUE TITLE
Long word lists cause exception

### ISSUE THREAD

**Issue by kilyig** [kilyig/MTP_Breaker#1]
Long files like [this](https://github.com/dolph/dictionary/blob/master/popular.txt) give the following error:
```
Traceback (most recent call last):
  File "otp_decrypter.py", line 73, in <module>
    if not checker.is_valid_prefix(curr_prefix + next_chars[ctext]):
  File "[path]/otp_phrase_checker.py", line 11, in is_valid_prefix
    return self._trie.starts_with(prefix)
  File "[path]/Trie.py", line 25, in starts_with
    if l not in current:
TypeError: argument of type 'int' is not iterable
```

**Comment by kilyig** [comment]
Was related to Trie.py. Changed `current[#]=1` to `current[#]={}`
